-- criação do banco de dados

-- MySQL Script generated by MySQL Workbench
-- Sat Jan 10 21:53:33 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema salaodebeleza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salaodebeleza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salaodebeleza` DEFAULT CHARACTER SET utf8 ;
USE `salaodebeleza` ;

-- -----------------------------------------------------
-- Table `salaodebeleza`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaodebeleza`.`Cliente` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaodebeleza`.`Profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaodebeleza`.`Profissional` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaodebeleza`.`Agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaodebeleza`.`Agendamento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  `data` DATE NOT NULL,
  `status` ENUM('agendado', 'confirmado', 'cancelado', 'finalizado') NOT NULL,
  `Cliente_ID` INT NOT NULL,
  `Profissional_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Agendamento_Cliente_idx` (`Cliente_ID` ASC) VISIBLE,
  INDEX `fk_Agendamento_Profissional1_idx` (`Profissional_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Agendamento_Cliente`
    FOREIGN KEY (`Cliente_ID`)
    REFERENCES `salaodebeleza`.`Cliente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agendamento_Profissional1`
    FOREIGN KEY (`Profissional_ID`)
    REFERENCES `salaodebeleza`.`Profissional` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaodebeleza`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaodebeleza`.`Pagamento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `data_pagamento` DATE NULL,
  `forma_pagamento` ENUM('dinheiro', 'credito', 'debito', 'pix') NULL,
  `status` ENUM('pendente', 'pago', 'cancelado') NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `Agendamento_ID` INT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Pagamento_Agendamento1_idx` (`Agendamento_ID` ASC) VISIBLE,
  UNIQUE INDEX `Agendamento_ID_UNIQUE` (`Agendamento_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Agendamento1`
    FOREIGN KEY (`Agendamento_ID`)
    REFERENCES `salaodebeleza`.`Agendamento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaodebeleza`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaodebeleza`.`Serviço` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descrição` VARCHAR(45) NOT NULL,
  `valor_base` DECIMAL(10,2) NOT NULL,
  `tempo_estimado` TIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaodebeleza`.`Profissional_Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaodebeleza`.`Profissional_Serviço` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Profissional_ID` INT NOT NULL,
  `Serviço_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Profissional_Serviço_Profissional1_idx` (`Profissional_ID` ASC) VISIBLE,
  INDEX `fk_Profissional_Serviço_Serviço1_idx` (`Serviço_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Profissional_Serviço_Profissional1`
    FOREIGN KEY (`Profissional_ID`)
    REFERENCES `salaodebeleza`.`Profissional` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profissional_Serviço_Serviço1`
    FOREIGN KEY (`Serviço_ID`)
    REFERENCES `salaodebeleza`.`Serviço` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaodebeleza`.`Serviço_Agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaodebeleza`.`Serviço_Agendamento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `duração` TIME NOT NULL,
  `Agendamento_ID` INT NOT NULL,
  `Serviço_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Serviço_Agendamento_Agendamento1_idx` (`Agendamento_ID` ASC) VISIBLE,
  INDEX `fk_Serviço_Agendamento_Serviço1_idx` (`Serviço_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Serviço_Agendamento_Agendamento1`
    FOREIGN KEY (`Agendamento_ID`)
    REFERENCES `salaodebeleza`.`Agendamento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serviço_Agendamento_Serviço1`
    FOREIGN KEY (`Serviço_ID`)
    REFERENCES `salaodebeleza`.`Serviço` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaodebeleza`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaodebeleza`.`Admin` (
  `ID` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
